const ISO_4217 = {
  list: [
    {
      Entity: "AFGHANISTAN",
      Currency: "Afghani",
      AlphabeticCode: "AFN",
    },
    {
      Entity: "Ã…LAND ISLANDS",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "ALBANIA",
      Currency: "Lek",
      AlphabeticCode: "ALL",
    },
    {
      Entity: "ALGERIA",
      Currency: "Algerian Dinar",
      AlphabeticCode: "DZD",
    },
    {
      Entity: "AMERICAN SAMOA",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
    },
    {
      Entity: "ANDORRA",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "ANGOLA",
      Currency: "Kwanza",
      AlphabeticCode: "AOA",
    },
    {
      Entity: "ANGUILLA",
      Currency: "East Caribbean Dollar",
      AlphabeticCode: "XCD",
    },
    {
      Entity: "ANTARCTICA",
      Currency: "No universal currency",
      AlphabeticCode: "",
    },
    {
      Entity: "ANTIGUA AND BARBUDA",
      Currency: "East Caribbean Dollar",
      AlphabeticCode: "XCD",
    },
    {
      Entity: "ARGENTINA",
      Currency: "Argentine Peso",
      AlphabeticCode: "ARS",
    },
    {
      Entity: "ARMENIA",
      Currency: "Armenian Dram",
      AlphabeticCode: "AMD",
    },
    {
      Entity: "ARUBA",
      Currency: "Aruban Florin",
      AlphabeticCode: "AWG",
    },
    {
      Entity: "AUSTRALIA",
      Currency: "Australian Dollar",
      AlphabeticCode: "AUD",
    },
    {
      Entity: "AUSTRIA",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "AZERBAIJAN",
      Currency: "Azerbaijanian Manat",
      AlphabeticCode: "AZN",
    },
    {
      Entity: "BAHAMAS (THE)",
      Currency: "Bahamian Dollar",
      AlphabeticCode: "BSD",
    },
    {
      Entity: "BAHRAIN",
      Currency: "Bahraini Dinar",
      AlphabeticCode: "BHD",
    },
    {
      Entity: "BANGLADESH",
      Currency: "Taka",
      AlphabeticCode: "BDT",
    },
    {
      Entity: "BARBADOS",
      Currency: "Barbados Dollar",
      AlphabeticCode: "BBD",
    },
    {
      Entity: "BELARUS",
      Currency: "Belarusian Ruble",
      AlphabeticCode: "BYN",
    },
    {
      Entity: "BELGIUM",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "BELIZE",
      Currency: "Belize Dollar",
      AlphabeticCode: "BZD",
    },
    {
      Entity: "BENIN",
      Currency: "CFA Franc BCEAO",
      AlphabeticCode: "XOF",
    },
    {
      Entity: "BERMUDA",
      Currency: "Bermudian Dollar",
      AlphabeticCode: "BMD",
    },
    {
      Entity: "BHUTAN",
      Currency: "Indian Rupee",
      AlphabeticCode: "INR",
      NumericCode: 356,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "BHUTAN",
      Currency: "Ngultrum",
      AlphabeticCode: "BTN",
    },
    {
      Entity: "BOLIVIA (PLURINATIONAL STATE OF)",
      Currency: "Boliviano",
      AlphabeticCode: "BOB",
    },
    {
      Entity: "BOLIVIA (PLURINATIONAL STATE OF)",
      Currency: "Mvdol",
      AlphabeticCode: "BOV",
    },
    {
      Entity: "BONAIRE, SINT EUSTATIUS AND SABA",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
    },
    {
      Entity: "BOSNIA AND HERZEGOVINA",
      Currency: "Convertible Mark",
      AlphabeticCode: "BAM",
    },
    {
      Entity: "BOTSWANA",
      Currency: "Pula",
      AlphabeticCode: "BWP",
    },
    {
      Entity: "BOUVET ISLAND",
      Currency: "Norwegian Krone",
      AlphabeticCode: "NOK",
    },
    {
      Entity: "BRAZIL",
      Currency: "Brazilian Real",
      AlphabeticCode: "BRL",
    },
    {
      Entity: "BRITISH INDIAN OCEAN TERRITORY (THE)",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
    },
    {
      Entity: "BRUNEI DARUSSALAM",
      Currency: "Brunei Dollar",
      AlphabeticCode: "BND",
    },
    {
      Entity: "BULGARIA",
      Currency: "Bulgarian Lev",
      AlphabeticCode: "BGN",
    },
    {
      Entity: "BURKINA FASO",
      Currency: "CFA Franc BCEAO",
      AlphabeticCode: "XOF",
      NumericCode: 952,
      MinorUnit: 0,
      WithdrawalDate: "",
    },
    {
      Entity: "BURUNDI",
      Currency: "Burundi Franc",
      AlphabeticCode: "BIF",
    },
    {
      Entity: "CABO VERDE",
      Currency: "Cabo Verde Escudo",
      AlphabeticCode: "CVE",
    },
    {
      Entity: "CAMBODIA",
      Currency: "Riel",
      AlphabeticCode: "KHR",
      NumericCode: 116,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "CAMEROON",
      Currency: "CFA Franc BEAC",
      AlphabeticCode: "XAF",
      NumericCode: 950,
      MinorUnit: 0,
      WithdrawalDate: "",
    },
    {
      Entity: "CANADA",
      Currency: "Canadian Dollar",
      AlphabeticCode: "CAD",
      NumericCode: 124,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "CAYMAN ISLANDS (THE)",
      Currency: "Cayman Islands Dollar",
      AlphabeticCode: "KYD",
      NumericCode: 136,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "CENTRAL AFRICAN REPUBLIC (THE)",
      Currency: "CFA Franc BEAC",
      AlphabeticCode: "XAF",
      NumericCode: 950,
      MinorUnit: 0,
      WithdrawalDate: "",
    },
    {
      Entity: "CHAD",
      Currency: "CFA Franc BEAC",
      AlphabeticCode: "XAF",
    },
    {
      Entity: "CHILE",
      Currency: "Chilean Peso",
      AlphabeticCode: "CLP",
    },
    {
      Entity: "CHILE",
      Currency: "Unidad de Fomento",
      AlphabeticCode: "CLF",
    },
    {
      Entity: "CHINA",
      Currency: "Yuan Renminbi",
      AlphabeticCode: "CNY",
    },
    {
      Entity: "CHRISTMAS ISLAND",
      Currency: "Australian Dollar",
      AlphabeticCode: "AUD",
      NumericCode: 36,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "COCOS (KEELING) ISLANDS (THE)",
      Currency: "Australian Dollar",
      AlphabeticCode: "AUD",
    },
    {
      Entity: "COLOMBIA",
      Currency: "Colombian Peso",
      AlphabeticCode: "COP",
    },
    {
      Entity: "COLOMBIA",
      Currency: "Unidad de Valor Real",
      AlphabeticCode: "COU",
    },
    {
      Entity: "COMOROS (THE)",
      Currency: "Comoro Franc",
      AlphabeticCode: "KMF",
    },
    {
      Entity: "CONGO (THE DEMOCRATIC REPUBLIC OF THE)",
      Currency: "Congolese Franc",
      AlphabeticCode: "CDF",
    },
    {
      Entity: "CONGO (THE)",
      Currency: "CFA Franc BEAC",
      AlphabeticCode: "XAF",
    },
    {
      Entity: "COOK ISLANDS (THE)",
      Currency: "New Zealand Dollar",
      AlphabeticCode: "NZD",
    },
    {
      Entity: "COSTA RICA",
      Currency: "Costa Rican Colon",
      AlphabeticCode: "CRC",
    },
    {
      Entity: "CÃ”TE D'IVOIRE",
      Currency: "CFA Franc BCEAO",
      AlphabeticCode: "XOF",
    },
    {
      Entity: "CROATIA",
      Currency: "Kuna",
      AlphabeticCode: "HRK",
    },
    {
      Entity: "CUBA",
      Currency: "Cuban Peso",
      AlphabeticCode: "CUP",
    },
    {
      Entity: "CUBA",
      Currency: "Peso Convertible",
      AlphabeticCode: "CUC",
    },
    {
      Entity: "CURAÃ‡AO",
      Currency: "Netherlands Antillean Guilder",
      AlphabeticCode: "ANG",
    },
    {
      Entity: "CYPRUS",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "CZECH REPUBLIC (THE)",
      Currency: "Czech Koruna",
      AlphabeticCode: "CZK",
    },
    {
      Entity: "DENMARK",
      Currency: "Danish Krone",
      AlphabeticCode: "DKK",
    },
    {
      Entity: "DJIBOUTI",
      Currency: "Djibouti Franc",
      AlphabeticCode: "DJF",
    },
    {
      Entity: "DOMINICA",
      Currency: "East Caribbean Dollar",
      AlphabeticCode: "XCD",
    },
    {
      Entity: "DOMINICAN REPUBLIC (THE)",
      Currency: "Dominican Peso",
      AlphabeticCode: "DOP",
    },
    {
      Entity: "ECUADOR",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
      NumericCode: 840,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "EGYPT",
      Currency: "Egyptian Pound",
      AlphabeticCode: "EGP",
      NumericCode: 818,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "EL SALVADOR",
      Currency: "El Salvador Colon",
      AlphabeticCode: "SVC",
      NumericCode: 222,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "EL SALVADOR",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
    },
    {
      Entity: "EQUATORIAL GUINEA",
      Currency: "CFA Franc BEAC",
      AlphabeticCode: "XAF",
    },
    {
      Entity: "ERITREA",
      Currency: "Nakfa",
      AlphabeticCode: "ERN",
    },
    {
      Entity: "ESTONIA",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "ETHIOPIA",
      Currency: "Ethiopian Birr",
      AlphabeticCode: "ETB",
    },
    {
      Entity: "EUROPEAN UNION",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "FALKLAND ISLANDS (THE) [MALVINAS]",
      Currency: "Falkland Islands Pound",
      AlphabeticCode: "FKP",
    },
    {
      Entity: "FAROE ISLANDS (THE)",
      Currency: "Danish Krone",
      AlphabeticCode: "DKK",
    },
    {
      Entity: "FIJI",
      Currency: "Fiji Dollar",
      AlphabeticCode: "FJD",
    },
    {
      Entity: "FINLAND",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "FRANCE",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "FRENCH GUIANA",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "FRENCH POLYNESIA",
      Currency: "CFP Franc",
      AlphabeticCode: "XPF",
    },
    {
      Entity: "FRENCH SOUTHERN TERRITORIES (THE)",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "GABON",
      Currency: "CFA Franc BEAC",
      AlphabeticCode: "XAF",
    },
    {
      Entity: "GAMBIA (THE)",
      Currency: "Dalasi",
      AlphabeticCode: "GMD",
    },
    {
      Entity: "GEORGIA",
      Currency: "Lari",
      AlphabeticCode: "GEL",
    },
    {
      Entity: "GERMANY",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "GHANA",
      Currency: "Ghana Cedi",
      AlphabeticCode: "GHS",
    },
    {
      Entity: "GIBRALTAR",
      Currency: "Gibraltar Pound",
      AlphabeticCode: "GIP",
    },
    {
      Entity: "GREECE",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "GREENLAND",
      Currency: "Danish Krone",
      AlphabeticCode: "DKK",
    },
    {
      Entity: "GRENADA",
      Currency: "East Caribbean Dollar",
      AlphabeticCode: "XCD",
    },
    {
      Entity: "GUADELOUPE",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "GUAM",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
    },
    {
      Entity: "GUATEMALA",
      Currency: "Quetzal",
      AlphabeticCode: "GTQ",
    },
    {
      Entity: "GUERNSEY",
      Currency: "Pound Sterling",
      AlphabeticCode: "GBP",
    },
    {
      Entity: "GUINEA",
      Currency: "Guinea Franc",
      AlphabeticCode: "GNF",
    },
    {
      Entity: "GUINEA-BISSAU",
      Currency: "CFA Franc BCEAO",
      AlphabeticCode: "XOF",
    },
    {
      Entity: "GUYANA",
      Currency: "Guyana Dollar",
      AlphabeticCode: "GYD",
    },
    {
      Entity: "HAITI",
      Currency: "Gourde",
      AlphabeticCode: "HTG",
    },
    {
      Entity: "HAITI",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
    },
    {
      Entity: "HEARD ISLAND AND McDONALD ISLANDS",
      Currency: "Australian Dollar",
      AlphabeticCode: "AUD",
    },
    {
      Entity: "HOLY SEE (THE)",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "HONDURAS",
      Currency: "Lempira",
      AlphabeticCode: "HNL",
    },
    {
      Entity: "HONG KONG",
      Currency: "Hong Kong Dollar",
      AlphabeticCode: "HKD",
    },
    {
      Entity: "HUNGARY",
      Currency: "Forint",
      AlphabeticCode: "HUF",
    },
    {
      Entity: "ICELAND",
      Currency: "Iceland Krona",
      AlphabeticCode: "ISK",
    },
    {
      Entity: "INDIA",
      Currency: "Indian Rupee",
      AlphabeticCode: "INR",
    },
    {
      Entity: "INDONESIA",
      Currency: "Rupiah",
      AlphabeticCode: "IDR",
    },
    {
      Entity: "INTERNATIONAL MONETARY FUND (IMF)",
      Currency: "SDR (Special Drawing Right)",
      AlphabeticCode: "XDR",
      NumericCode: 960,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "IRAN (ISLAMIC REPUBLIC OF)",
      Currency: "Iranian Rial",
      AlphabeticCode: "IRR",
      NumericCode: 364,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "IRAQ",
      Currency: "Iraqi Dinar",
      AlphabeticCode: "IQD",
      NumericCode: 368,
      MinorUnit: 3,
      WithdrawalDate: "",
    },
    {
      Entity: "IRELAND",
      Currency: "Euro",
      AlphabeticCode: "EUR",
      NumericCode: 978,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "ISLE OF MAN",
      Currency: "Pound Sterling",
      AlphabeticCode: "GBP",
      NumericCode: 826,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "ISRAEL",
      Currency: "New Israeli Sheqel",
      AlphabeticCode: "ILS",
      NumericCode: 376,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "ITALY",
      Currency: "Euro",
      AlphabeticCode: "EUR",
      NumericCode: 978,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "JAMAICA",
      Currency: "Jamaican Dollar",
      AlphabeticCode: "JMD",
    },
    {
      Entity: "JAPAN",
      Currency: "Yen",
      AlphabeticCode: "JPY",
    },
    {
      Entity: "JERSEY",
      Currency: "Pound Sterling",
      AlphabeticCode: "GBP",
    },
    {
      Entity: "JORDAN",
      Currency: "Jordanian Dinar",
      AlphabeticCode: "JOD",
    },
    {
      Entity: "KAZAKHSTAN",
      Currency: "Tenge",
      AlphabeticCode: "KZT",
    },
    {
      Entity: "KENYA",
      Currency: "Kenyan Shilling",
      AlphabeticCode: "KES",
    },
    {
      Entity: "KIRIBATI",
      Currency: "Australian Dollar",
      AlphabeticCode: "AUD",
    },
    {
      Entity: "KOREA (THE DEMOCRATIC PEOPLEâ€™S REPUBLIC OF)",
      Currency: "North Korean Won",
      AlphabeticCode: "KPW",
      NumericCode: 408,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "KOREA (THE REPUBLIC OF)",
      Currency: "Won",
      AlphabeticCode: "KRW",
    },
    {
      Entity: "KUWAIT",
      Currency: "Kuwaiti Dinar",
      AlphabeticCode: "KWD",
    },
    {
      Entity: "KYRGYZSTAN",
      Currency: "Som",
      AlphabeticCode: "KGS",
    },
    {
      Entity: "LAO PEOPLEâ€™S DEMOCRATIC REPUBLIC (THE)",
      Currency: "Kip",
      AlphabeticCode: "LAK",
    },
    {
      Entity: "LATVIA",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "LEBANON",
      Currency: "Lebanese Pound",
      AlphabeticCode: "LBP",
    },
    {
      Entity: "LESOTHO",
      Currency: "Loti",
      AlphabeticCode: "LSL",
    },
    {
      Entity: "LESOTHO",
      Currency: "Rand",
      AlphabeticCode: "ZAR",
    },
    {
      Entity: "LIBERIA",
      Currency: "Liberian Dollar",
      AlphabeticCode: "LRD",
    },
    {
      Entity: "LIBYA",
      Currency: "Libyan Dinar",
      AlphabeticCode: "LYD",
    },
    {
      Entity: "LIECHTENSTEIN",
      Currency: "Swiss Franc",
      AlphabeticCode: "CHF",
    },
    {
      Entity: "LITHUANIA",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "LUXEMBOURG",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "MACAO",
      Currency: "Pataca",
      AlphabeticCode: "MOP",
    },
    {
      Entity: "MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)",
      Currency: "Denar",
      AlphabeticCode: "MKD",
    },
    {
      Entity: "MADAGASCAR",
      Currency: "Malagasy Ariary",
      AlphabeticCode: "MGA",
    },
    {
      Entity: "MALAWI",
      Currency: "Malawi Kwacha",
      AlphabeticCode: "MWK",
      NumericCode: 454,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "MALAYSIA",
      Currency: "Malaysian Ringgit",
      AlphabeticCode: "MYR",
      NumericCode: 458,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "MALDIVES",
      Currency: "Rufiyaa",
      AlphabeticCode: "MVR",
      NumericCode: 462,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "MALI",
      Currency: "CFA Franc BCEAO",
      AlphabeticCode: "XOF",
      NumericCode: 952,
      MinorUnit: 0,
      WithdrawalDate: "",
    },
    {
      Entity: "MALTA",
      Currency: "Euro",
      AlphabeticCode: "EUR",
      NumericCode: 978,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "MARSHALL ISLANDS (THE)",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
      NumericCode: 840,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "MARTINIQUE",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "MAURITANIA",
      Currency: "Ouguiya",
      AlphabeticCode: "MRO",
    },
    {
      Entity: "MAURITIUS",
      Currency: "Mauritius Rupee",
      AlphabeticCode: "MUR",
    },
    {
      Entity: "MAYOTTE",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP",
      Currency: "ADB Unit of Account",
      AlphabeticCode: "XUA",
    },
    {
      Entity: "MEXICO",
      Currency: "Mexican Peso",
      AlphabeticCode: "MXN",
    },
    {
      Entity: "MEXICO",
      Currency: "Mexican Unidad de Inversion (UDI)",
      AlphabeticCode: "MXV",
    },
    {
      Entity: "MICRONESIA (FEDERATED STATES OF)",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
    },
    {
      Entity: "MOLDOVA (THE REPUBLIC OF)",
      Currency: "Moldovan Leu",
      AlphabeticCode: "MDL",
    },
    {
      Entity: "MONACO",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "MONGOLIA",
      Currency: "Tugrik",
      AlphabeticCode: "MNT",
    },
    {
      Entity: "MONTENEGRO",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "MONTSERRAT",
      Currency: "East Caribbean Dollar",
      AlphabeticCode: "XCD",
    },
    {
      Entity: "MOROCCO",
      Currency: "Moroccan Dirham",
      AlphabeticCode: "MAD",
    },
    {
      Entity: "MOZAMBIQUE",
      Currency: "Mozambique Metical",
      AlphabeticCode: "MZN",
    },
    {
      Entity: "MYANMAR",
      Currency: "Kyat",
      AlphabeticCode: "MMK",
    },
    {
      Entity: "NAMIBIA",
      Currency: "Namibia Dollar",
      AlphabeticCode: "NAD",
    },
    {
      Entity: "NAMIBIA",
      Currency: "Rand",
      AlphabeticCode: "ZAR",
    },
    {
      Entity: "NAURU",
      Currency: "Australian Dollar",
      AlphabeticCode: "AUD",
    },
    {
      Entity: "NEPAL",
      Currency: "Nepalese Rupee",
      AlphabeticCode: "NPR",
    },
    {
      Entity: "NETHERLANDS (THE)",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "NEW CALEDONIA",
      Currency: "CFP Franc",
      AlphabeticCode: "XPF",
    },
    {
      Entity: "NEW ZEALAND",
      Currency: "New Zealand Dollar",
      AlphabeticCode: "NZD",
    },
    {
      Entity: "NICARAGUA",
      Currency: "Cordoba Oro",
      AlphabeticCode: "NIO",
    },
    {
      Entity: "NIGER (THE)",
      Currency: "CFA Franc BCEAO",
      AlphabeticCode: "XOF",
    },
    {
      Entity: "NIGERIA",
      Currency: "Naira",
      AlphabeticCode: "NGN",
    },
    {
      Entity: "NIUE",
      Currency: "New Zealand Dollar",
      AlphabeticCode: "NZD",
      NumericCode: 554,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "NORFOLK ISLAND",
      Currency: "Australian Dollar",
      AlphabeticCode: "AUD",
    },
    {
      Entity: "NORTHERN MARIANA ISLANDS (THE)",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
    },
    {
      Entity: "NORWAY",
      Currency: "Norwegian Krone",
      AlphabeticCode: "NOK",
      NumericCode: 578,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "OMAN",
      Currency: "Rial Omani",
      AlphabeticCode: "OMR",
      NumericCode: 512,
      MinorUnit: 3,
      WithdrawalDate: "",
    },
    {
      Entity: "PAKISTAN",
      Currency: "Pakistan Rupee",
      AlphabeticCode: "PKR",
    },
    {
      Entity: "PALAU",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
    },
    {
      Entity: "PALESTINE, STATE OF",
      Currency: "No universal currency",
      AlphabeticCode: "",
    },
    {
      Entity: "PANAMA",
      Currency: "Balboa",
      AlphabeticCode: "PAB",
    },
    {
      Entity: "PANAMA",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
    },
    {
      Entity: "PAPUA NEW GUINEA",
      Currency: "Kina",
      AlphabeticCode: "PGK",
    },
    {
      Entity: "PARAGUAY",
      Currency: "Guarani",
      AlphabeticCode: "PYG",
    },
    {
      Entity: "PERU",
      Currency: "Sol",
      AlphabeticCode: "PEN",
    },
    {
      Entity: "PHILIPPINES (THE)",
      Currency: "Philippine Peso",
      AlphabeticCode: "PHP",
    },
    {
      Entity: "PITCAIRN",
      Currency: "New Zealand Dollar",
      AlphabeticCode: "NZD",
    },
    {
      Entity: "POLAND",
      Currency: "Zloty",
      AlphabeticCode: "PLN",
    },
    {
      Entity: "PORTUGAL",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "PUERTO RICO",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
    },
    {
      Entity: "QATAR",
      Currency: "Qatari Rial",
      AlphabeticCode: "QAR",
    },
    {
      Entity: "RÃ‰UNION",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "ROMANIA",
      Currency: "Romanian Leu",
      AlphabeticCode: "RON",
    },
    {
      Entity: "RUSSIAN FEDERATION (THE)",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUB",
    },
    {
      Entity: "RWANDA",
      Currency: "Rwanda Franc",
      AlphabeticCode: "RWF",
    },
    {
      Entity: "SAINT BARTHÃ‰LEMY",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
      Currency: "Saint Helena Pound",
      AlphabeticCode: "SHP",
    },
    {
      Entity: "SAINT KITTS AND NEVIS",
      Currency: "East Caribbean Dollar",
      AlphabeticCode: "XCD",
    },
    {
      Entity: "SAINT LUCIA",
      Currency: "East Caribbean Dollar",
      AlphabeticCode: "XCD",
      NumericCode: 951,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SAINT MARTIN (FRENCH PART)",
      Currency: "Euro",
      AlphabeticCode: "EUR",
      NumericCode: 978,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SAINT PIERRE AND MIQUELON",
      Currency: "Euro",
      AlphabeticCode: "EUR",
      NumericCode: 978,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SAINT VINCENT AND THE GRENADINES",
      Currency: "East Caribbean Dollar",
      AlphabeticCode: "XCD",
      NumericCode: 951,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SAMOA",
      Currency: "Tala",
      AlphabeticCode: "WST",
      NumericCode: 882,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SAN MARINO",
      Currency: "Euro",
      AlphabeticCode: "EUR",
      NumericCode: 978,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SAO TOME AND PRINCIPE",
      Currency: "Dobra",
      AlphabeticCode: "STD",
      NumericCode: 678,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SAUDI ARABIA",
      Currency: "Saudi Riyal",
      AlphabeticCode: "SAR",
      NumericCode: 682,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SENEGAL",
      Currency: "CFA Franc BCEAO",
      AlphabeticCode: "XOF",
      NumericCode: 952,
      MinorUnit: 0,
      WithdrawalDate: "",
    },
    {
      Entity: "SERBIA",
      Currency: "Serbian Dinar",
      AlphabeticCode: "RSD",
      NumericCode: 941,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SEYCHELLES",
      Currency: "Seychelles Rupee",
      AlphabeticCode: "SCR",
      NumericCode: 690,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SIERRA LEONE",
      Currency: "Leone",
      AlphabeticCode: "SLL",
      NumericCode: 694,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SINGAPORE",
      Currency: "Singapore Dollar",
      AlphabeticCode: "SGD",
      NumericCode: 702,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SINT MAARTEN (DUTCH PART)",
      Currency: "Netherlands Antillean Guilder",
      AlphabeticCode: "ANG",
      NumericCode: 532,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE',
      Currency: "Sucre",
      AlphabeticCode: "XSU",
      NumericCode: 994,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "SLOVAKIA",
      Currency: "Euro",
      AlphabeticCode: "EUR",
      NumericCode: 978,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SLOVENIA",
      Currency: "Euro",
      AlphabeticCode: "EUR",
      NumericCode: 978,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SOLOMON ISLANDS",
      Currency: "Solomon Islands Dollar",
      AlphabeticCode: "SBD",
      NumericCode: 90,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SOMALIA",
      Currency: "Somali Shilling",
      AlphabeticCode: "SOS",
      NumericCode: 706,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SOUTH AFRICA",
      Currency: "Rand",
      AlphabeticCode: "ZAR",
      NumericCode: 710,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
      Currency: "No universal currency",
      AlphabeticCode: "",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "",
    },
    {
      Entity: "SOUTH SUDAN",
      Currency: "South Sudanese Pound",
      AlphabeticCode: "SSP",
      NumericCode: 728,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SPAIN",
      Currency: "Euro",
      AlphabeticCode: "EUR",
      NumericCode: 978,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SRI LANKA",
      Currency: "Sri Lanka Rupee",
      AlphabeticCode: "LKR",
      NumericCode: 144,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SUDAN (THE)",
      Currency: "Sudanese Pound",
      AlphabeticCode: "SDG",
      NumericCode: 938,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SURINAME",
      Currency: "Surinam Dollar",
      AlphabeticCode: "SRD",
      NumericCode: 968,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SVALBARD AND JAN MAYEN",
      Currency: "Norwegian Krone",
      AlphabeticCode: "NOK",
      NumericCode: 578,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SWAZILAND",
      Currency: "Lilangeni",
      AlphabeticCode: "SZL",
      NumericCode: 748,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SWEDEN",
      Currency: "Swedish Krona",
      AlphabeticCode: "SEK",
      NumericCode: 752,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SWITZERLAND",
      Currency: "Swiss Franc",
      AlphabeticCode: "CHF",
      NumericCode: 756,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SWITZERLAND",
      Currency: "WIR Euro",
      AlphabeticCode: "CHE",
      NumericCode: 947,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SWITZERLAND",
      Currency: "WIR Franc",
      AlphabeticCode: "CHW",
      NumericCode: 948,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "SYRIAN ARAB REPUBLIC",
      Currency: "Syrian Pound",
      AlphabeticCode: "SYP",
      NumericCode: 760,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "TAIWAN (PROVINCE OF CHINA)",
      Currency: "New Taiwan Dollar",
      AlphabeticCode: "TWD",
      NumericCode: 901,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "TAJIKISTAN",
      Currency: "Somoni",
      AlphabeticCode: "TJS",
      NumericCode: 972,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "TANZANIA, UNITED REPUBLIC OF",
      Currency: "Tanzanian Shilling",
      AlphabeticCode: "TZS",
      NumericCode: 834,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "THAILAND",
      Currency: "Baht",
      AlphabeticCode: "THB",
      NumericCode: 764,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "TIMOR-LESTE",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
      NumericCode: 840,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "TOGO",
      Currency: "CFA Franc BCEAO",
      AlphabeticCode: "XOF",
      NumericCode: 952,
      MinorUnit: 0,
      WithdrawalDate: "",
    },
    {
      Entity: "TOKELAU",
      Currency: "New Zealand Dollar",
      AlphabeticCode: "NZD",
      NumericCode: 554,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "TONGA",
      Currency: "Paâ€™anga",
      AlphabeticCode: "TOP",
      NumericCode: 776,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "TRINIDAD AND TOBAGO",
      Currency: "Trinidad and Tobago Dollar",
      AlphabeticCode: "TTD",
      NumericCode: 780,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "TUNISIA",
      Currency: "Tunisian Dinar",
      AlphabeticCode: "TND",
      NumericCode: 788,
      MinorUnit: 3,
      WithdrawalDate: "",
    },
    {
      Entity: "TURKEY",
      Currency: "Turkish Lira",
      AlphabeticCode: "TRY",
      NumericCode: 949,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "TURKMENISTAN",
      Currency: "Turkmenistan New Manat",
      AlphabeticCode: "TMT",
      NumericCode: 934,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "TURKS AND CAICOS ISLANDS (THE)",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
      NumericCode: 840,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "TUVALU",
      Currency: "Australian Dollar",
      AlphabeticCode: "AUD",
      NumericCode: 36,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "UGANDA",
      Currency: "Uganda Shilling",
      AlphabeticCode: "UGX",
      NumericCode: 800,
      MinorUnit: 0,
      WithdrawalDate: "",
    },
    {
      Entity: "UKRAINE",
      Currency: "Hryvnia",
      AlphabeticCode: "UAH",
      NumericCode: 980,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "UNITED ARAB EMIRATES (THE)",
      Currency: "UAE Dirham",
      AlphabeticCode: "AED",
      NumericCode: 784,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)",
      Currency: "Pound Sterling",
      AlphabeticCode: "GBP",
      NumericCode: 826,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "UNITED STATES MINOR OUTLYING ISLANDS (THE)",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
      NumericCode: 840,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "UNITED STATES OF AMERICA (THE)",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
      NumericCode: 840,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "UNITED STATES OF AMERICA (THE)",
      Currency: "US Dollar (Next day)",
      AlphabeticCode: "USN",
      NumericCode: 997,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "URUGUAY",
      Currency: "Peso Uruguayo",
      AlphabeticCode: "UYU",
      NumericCode: 858,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "URUGUAY",
      Currency: "Uruguay Peso en Unidades Indexadas (URUIURUI)",
      AlphabeticCode: "UYI",
      NumericCode: 940,
      MinorUnit: 0,
      WithdrawalDate: "",
    },
    {
      Entity: "UZBEKISTAN",
      Currency: "Uzbekistan Sum",
      AlphabeticCode: "UZS",
      NumericCode: 860,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "VANUATU",
      Currency: "Vatu",
      AlphabeticCode: "VUV",
      NumericCode: 548,
      MinorUnit: 0,
      WithdrawalDate: "",
    },
    {
      Entity: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
      Currency: "BolÃ­var",
      AlphabeticCode: "VEF",
      NumericCode: 937,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "VIET NAM",
      Currency: "Dong",
      AlphabeticCode: "VND",
      NumericCode: 704,
      MinorUnit: 0,
      WithdrawalDate: "",
    },
    {
      Entity: "VIRGIN ISLANDS (BRITISH)",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
      NumericCode: 840,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "VIRGIN ISLANDS (U.S.)",
      Currency: "US Dollar",
      AlphabeticCode: "USD",
      NumericCode: 840,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "WALLIS AND FUTUNA",
      Currency: "CFP Franc",
      AlphabeticCode: "XPF",
      NumericCode: 953,
      MinorUnit: 0,
      WithdrawalDate: "",
    },
    {
      Entity: "WESTERN SAHARA",
      Currency: "Moroccan Dirham",
      AlphabeticCode: "MAD",
      NumericCode: 504,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "YEMEN",
      Currency: "Yemeni Rial",
      AlphabeticCode: "YER",
      NumericCode: 886,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "ZAMBIA",
      Currency: "Zambian Kwacha",
      AlphabeticCode: "ZMW",
      NumericCode: 967,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "ZIMBABWE",
      Currency: "Zimbabwe Dollar",
      AlphabeticCode: "ZWL",
      NumericCode: 932,
      MinorUnit: 2,
      WithdrawalDate: "",
    },
    {
      Entity: "ZZ01_Bond Markets Unit European_EURCO",
      Currency: "Bond Markets Unit European Composite Unit (EURCO)",
      AlphabeticCode: "XBA",
      NumericCode: 955,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "ZZ02_Bond Markets Unit European_EMU-6",
      Currency: "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
      AlphabeticCode: "XBB",
      NumericCode: 956,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "ZZ03_Bond Markets Unit European_EUA-9",
      Currency: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
      AlphabeticCode: "XBC",
      NumericCode: 957,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "ZZ04_Bond Markets Unit European_EUA-17",
      Currency: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
      AlphabeticCode: "XBD",
      NumericCode: 958,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "ZZ06_Testing_Code",
      Currency: "Codes specifically reserved for testing purposes",
      AlphabeticCode: "XTS",
      NumericCode: 963,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "ZZ07_No_Currency",
      Currency:
        "The codes assigned for transactions where no currency is involved",
      AlphabeticCode: "XXX",
      NumericCode: 999,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "ZZ08_Gold",
      Currency: "Gold",
      AlphabeticCode: "XAU",
      NumericCode: 959,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "ZZ09_Palladium",
      Currency: "Palladium",
      AlphabeticCode: "XPD",
      NumericCode: 964,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "ZZ10_Platinum",
      Currency: "Platinum",
      AlphabeticCode: "XPT",
      NumericCode: 962,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "ZZ11_Silver",
      Currency: "Silver",
      AlphabeticCode: "XAG",
      NumericCode: 961,
      MinorUnit: "-",
      WithdrawalDate: "",
    },
    {
      Entity: "AFGHANISTAN",
      Currency: "Afghani",
      AlphabeticCode: "AFA",
      NumericCode: 4,
      MinorUnit: "",
      WithdrawalDate: "2003-01",
    },
    {
      Entity: "Ã…LAND ISLANDS",
      Currency: "Markka",
      AlphabeticCode: "FIM",
      NumericCode: 246,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "ALBANIA",
      Currency: "Old Lek",
      AlphabeticCode: "ALK",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1989-12",
    },
    {
      Entity: "ANDORRA",
      Currency: "Andorran Peseta",
      AlphabeticCode: "ADP",
      NumericCode: 20,
      MinorUnit: "",
      WithdrawalDate: "2003-07",
    },
    {
      Entity: "ANDORRA",
      Currency: "Spanish Peseta",
      AlphabeticCode: "ESP",
      NumericCode: 724,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "ANDORRA",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
      NumericCode: 250,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "ANGOLA",
      Currency: "Kwanza",
      AlphabeticCode: "AOK",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1991-03",
    },
    {
      Entity: "ANGOLA",
      Currency: "New Kwanza",
      AlphabeticCode: "AON",
      NumericCode: 24,
      MinorUnit: "",
      WithdrawalDate: "2000-02",
    },
    {
      Entity: "ANGOLA",
      Currency: "Kwanza Reajustado",
      AlphabeticCode: "AOR",
      NumericCode: 982,
      MinorUnit: "",
      WithdrawalDate: "2000-02",
    },
    {
      Entity: "ARGENTINA",
      Currency: "Austral",
      AlphabeticCode: "ARA",
      NumericCode: 32,
      MinorUnit: "",
      WithdrawalDate: "1992-01",
    },
    {
      Entity: "ARGENTINA",
      Currency: "Peso Argentino",
      AlphabeticCode: "ARP",
      NumericCode: 32,
      MinorUnit: "",
      WithdrawalDate: "1985-07",
    },
    {
      Entity: "ARGENTINA",
      Currency: "Peso",
      AlphabeticCode: "ARY",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1989 to 1990",
    },
    {
      Entity: "ARMENIA",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUR",
      NumericCode: 810,
      MinorUnit: "",
      WithdrawalDate: "1994-08",
    },
    {
      Entity: "AUSTRIA",
      Currency: "Schilling",
      AlphabeticCode: "ATS",
      NumericCode: 40,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "AZERBAIJAN",
      Currency: "Azerbaijan Manat",
      AlphabeticCode: "AYM",
      NumericCode: 945,
      MinorUnit: "",
      WithdrawalDate: "2005-10",
    },
    {
      Entity: "AZERBAIJAN",
      Currency: "Azerbaijanian Manat",
      AlphabeticCode: "AZM",
      NumericCode: 31,
      MinorUnit: "",
      WithdrawalDate: "2005-12",
    },
    {
      Entity: "AZERBAIJAN",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUR",
      NumericCode: 810,
      MinorUnit: "",
      WithdrawalDate: "1994-08",
    },
    {
      Entity: "BELARUS",
      Currency: "Belarusian Ruble",
      AlphabeticCode: "BYR",
      NumericCode: 974,
      MinorUnit: "",
      WithdrawalDate: "2017-01",
    },
    {
      Entity: "BELARUS",
      Currency: "Belarusian Ruble",
      AlphabeticCode: "BYB",
      NumericCode: 112,
      MinorUnit: "",
      WithdrawalDate: "2001-01",
    },
    {
      Entity: "BELARUS",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUR",
      NumericCode: 810,
      MinorUnit: "",
      WithdrawalDate: "1994-06",
    },
    {
      Entity: "BELGIUM",
      Currency: "Convertible Franc",
      AlphabeticCode: "BEC",
      NumericCode: 993,
      MinorUnit: "",
      WithdrawalDate: "1990-03",
    },
    {
      Entity: "BELGIUM",
      Currency: "Belgian Franc",
      AlphabeticCode: "BEF",
      NumericCode: 56,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "BELGIUM",
      Currency: "Financial Franc",
      AlphabeticCode: "BEL",
      NumericCode: 992,
      MinorUnit: "",
      WithdrawalDate: "1990-03",
    },
    {
      Entity: "BOLIVIA",
      Currency: "Peso boliviano",
      AlphabeticCode: "BOP",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1987-02",
    },
    {
      Entity: "BOSNIA AND HERZEGOVINA",
      Currency: "Dinar",
      AlphabeticCode: "BAD",
      NumericCode: 70,
      MinorUnit: "",
      WithdrawalDate: "1998-07",
    },
    {
      Entity: "BRAZIL",
      Currency: "Cruzeiro",
      AlphabeticCode: "BRB",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1986-03",
    },
    {
      Entity: "BRAZIL",
      Currency: "Cruzado",
      AlphabeticCode: "BRC",
      NumericCode: 76,
      MinorUnit: "",
      WithdrawalDate: "1989-02",
    },
    {
      Entity: "BRAZIL",
      Currency: "Cruzeiro",
      AlphabeticCode: "BRE",
      NumericCode: 76,
      MinorUnit: "",
      WithdrawalDate: "1993-03",
    },
    {
      Entity: "BRAZIL",
      Currency: "New Cruzado",
      AlphabeticCode: "BRN",
      NumericCode: 76,
      MinorUnit: "",
      WithdrawalDate: "1990-03",
    },
    {
      Entity: "BRAZIL",
      Currency: "Cruzeiro Real",
      AlphabeticCode: "BRR",
      NumericCode: 987,
      MinorUnit: "",
      WithdrawalDate: "1994-07",
    },
    {
      Entity: "BULGARIA",
      Currency: "Lev A/52",
      AlphabeticCode: "BGJ",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1989 to 1990",
    },
    {
      Entity: "BULGARIA",
      Currency: "Lev A/62",
      AlphabeticCode: "BGK",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1989 to 1990",
    },
    {
      Entity: "BULGARIA",
      Currency: "Lev",
      AlphabeticCode: "BGL",
      NumericCode: 100,
      MinorUnit: "",
      WithdrawalDate: "2003-11",
    },
    {
      Entity: "BURMA",
      Currency: "-",
      AlphabeticCode: "BUK",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1990-02",
    },
    {
      Entity: "CHINA",
      Currency: "Peoples Bank Dollar",
      AlphabeticCode: "CNX",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1989-12",
    },
    {
      Entity: "CROATIA",
      Currency: "Croatian Dinar",
      AlphabeticCode: "HRD",
      NumericCode: 191,
      MinorUnit: "",
      WithdrawalDate: "1995-01",
    },
    {
      Entity: "CROATIA",
      Currency: "Croatian Kuna",
      AlphabeticCode: "HRK",
      NumericCode: 191,
      MinorUnit: "",
      WithdrawalDate: "2015-06",
    },
    {
      Entity: "CYPRUS",
      Currency: "Cyprus Pound",
      AlphabeticCode: "CYP",
      NumericCode: 196,
      MinorUnit: "",
      WithdrawalDate: "2008-01",
    },
    {
      Entity: "CZECHOSLOVAKIA",
      Currency: "Krona A/53",
      AlphabeticCode: "CSJ",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1989 to 1990",
    },
    {
      Entity: "CZECHOSLOVAKIA",
      Currency: "Koruna",
      AlphabeticCode: "CSK",
      NumericCode: 200,
      MinorUnit: "",
      WithdrawalDate: "1993-03",
    },
    {
      Entity: "ECUADOR",
      Currency: "Sucre",
      AlphabeticCode: "ECS",
      NumericCode: 218,
      MinorUnit: "",
      WithdrawalDate: "2000-09",
    },
    {
      Entity: "ECUADOR",
      Currency: "Unidad de Valor Constante (UVC)",
      AlphabeticCode: "ECV",
      NumericCode: 983,
      MinorUnit: "",
      WithdrawalDate: "2000-09",
    },
    {
      Entity: "EQUATORIAL GUINEA",
      Currency: "Ekwele",
      AlphabeticCode: "GQE",
      NumericCode: 226,
      MinorUnit: "",
      WithdrawalDate: "1986-06",
    },
    {
      Entity: "ESTONIA",
      Currency: "Kroon",
      AlphabeticCode: "EEK",
      NumericCode: 233,
      MinorUnit: "",
      WithdrawalDate: "2011-01",
    },
    {
      Entity: "EUROPEAN MONETARY CO-OPERATION FUND (EMCF)",
      Currency: "European Currency Unit (E.C.U)",
      AlphabeticCode: "XEU",
      NumericCode: 954,
      MinorUnit: "",
      WithdrawalDate: "1999-01",
    },
    {
      Entity: "FINLAND",
      Currency: "Markka",
      AlphabeticCode: "FIM",
      NumericCode: 246,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "FRANCE",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
      NumericCode: 250,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "FRENCH  GUIANA",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
      NumericCode: 250,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "FRENCH SOUTHERN TERRITORIES",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
      NumericCode: 250,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "GEORGIA",
      Currency: "Georgian Coupon",
      AlphabeticCode: "GEK",
      NumericCode: 268,
      MinorUnit: "",
      WithdrawalDate: "1995-10",
    },
    {
      Entity: "GEORGIA",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUR",
      NumericCode: 810,
      MinorUnit: "",
      WithdrawalDate: "1994-04",
    },
    {
      Entity: "GERMAN DEMOCRATIC REPUBLIC",
      Currency: "Mark der DDR",
      AlphabeticCode: "DDM",
      NumericCode: 278,
      MinorUnit: "",
      WithdrawalDate: "1990-07 to 1990-09",
    },
    {
      Entity: "GERMANY",
      Currency: "Deutsche Mark",
      AlphabeticCode: "DEM",
      NumericCode: 276,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "GHANA",
      Currency: "Cedi",
      AlphabeticCode: "GHC",
      NumericCode: 288,
      MinorUnit: "",
      WithdrawalDate: "2008-01",
    },
    {
      Entity: "GHANA",
      Currency: "Ghana Cedi",
      AlphabeticCode: "GHP",
      NumericCode: 939,
      MinorUnit: "",
      WithdrawalDate: "2007-06",
    },
    {
      Entity: "GREECE",
      Currency: "Drachma",
      AlphabeticCode: "GRD",
      NumericCode: 300,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "GUADELOUPE",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
      NumericCode: 250,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "GUINEA",
      Currency: "Syli",
      AlphabeticCode: "GNE",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1989-12",
    },
    {
      Entity: "GUINEA",
      Currency: "Syli",
      AlphabeticCode: "GNS",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1986-02",
    },
    {
      Entity: "GUINEA-BISSAU",
      Currency: "Guinea Escudo",
      AlphabeticCode: "GWE",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1978 to 1981",
    },
    {
      Entity: "GUINEA-BISSAU",
      Currency: "Guinea-Bissau Peso",
      AlphabeticCode: "GWP",
      NumericCode: 624,
      MinorUnit: "",
      WithdrawalDate: "1997-05",
    },
    {
      Entity: "HOLY SEE (VATICAN CITY STATE)",
      Currency: "Italian Lira",
      AlphabeticCode: "ITL",
      NumericCode: 380,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "ICELAND",
      Currency: "Old Krona",
      AlphabeticCode: "ISJ",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1989 to 1990",
    },
    {
      Entity: "IRELAND",
      Currency: "Irish Pound",
      AlphabeticCode: "IEP",
      NumericCode: 372,
      MinorUnit: "",
      WithdrawalDate: "2002-03",
    },
    {
      Entity: "ISRAEL",
      Currency: "Pound",
      AlphabeticCode: "ILP",
      NumericCode: "",
      MinorUnit: "",
      WithdrawalDate: "1978 to 1981",
    },
    {
      Entity: "ISRAEL",
      Currency: "Old Shekel",
      AlphabeticCode: "ILR",
    },
    {
      Entity: "ITALY",
      Currency: "Italian Lira",
      AlphabeticCode: "ITL",
    },
    {
      Entity: "KAZAKHSTAN",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUR",
    },
    {
      Entity: "KYRGYZSTAN",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUR",
    },
    {
      Entity: "LAO",
      Currency: "Kip Pot Pol",
      AlphabeticCode: "LAJ",
    },
    {
      Entity: "LATVIA",
      Currency: "Latvian Lats",
      AlphabeticCode: "LVL",
    },
    {
      Entity: "LATVIA",
      Currency: "Latvian Ruble",
      AlphabeticCode: "LVR",
    },
    {
      Entity: "LESOTHO",
      Currency: "Maloti",
      AlphabeticCode: "LSM",
    },
    {
      Entity: "LESOTHO",
      Currency: "Financial Rand",
      AlphabeticCode: "ZAL",
    },
    {
      Entity: "LITHUANIA",
      Currency: "Lithuanian Litas",
      AlphabeticCode: "LTL",
    },
    {
      Entity: "LITHUANIA",
      Currency: "Talonas",
      AlphabeticCode: "LTT",
    },
    {
      Entity: "LUXEMBOURG",
      Currency: "Luxembourg Convertible Franc",
      AlphabeticCode: "LUC",
    },
    {
      Entity: "LUXEMBOURG",
      Currency: "Luxembourg Franc",
      AlphabeticCode: "LUF",
    },
    {
      Entity: "LUXEMBOURG",
      Currency: "Luxembourg Financial Franc",
      AlphabeticCode: "LUL",
    },
    {
      Entity: "MADAGASCAR",
      Currency: "Malagasy Franc",
      AlphabeticCode: "MGF",
    },
    {
      Entity: "MALAWI",
      Currency: "Kwacha",
      AlphabeticCode: "MWK",
    },
    {
      Entity: "MALDIVES",
      Currency: "Maldive Rupee",
      AlphabeticCode: "MVQ",
    },
    {
      Entity: "MALI",
      Currency: "Mali Franc",
      AlphabeticCode: "MLF",
    },
    {
      Entity: "MALTA",
      Currency: "Maltese Lira",
      AlphabeticCode: "MTL",
    },
    {
      Entity: "MALTA",
      Currency: "Maltese Pound",
      AlphabeticCode: "MTP",
    },
    {
      Entity: "MARTINIQUE",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
    },
    {
      Entity: "MAYOTTE",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
    },
    {
      Entity: "MEXICO",
      Currency: "Mexican Peso",
      AlphabeticCode: "MXP",
    },
    {
      Entity: "MOLDOVA, REPUBLIC OF",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUR",
    },
    {
      Entity: "MONACO",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
    },
    {
      Entity: "MOZAMBIQUE",
      Currency: "Mozambique Escudo",
      AlphabeticCode: "MZE",
    },
    {
      Entity: "MOZAMBIQUE",
      Currency: "Mozambique Metical",
      AlphabeticCode: "MZM",
    },
    {
      Entity: "NETHERLANDS",
      Currency: "Netherlands Guilder",
      AlphabeticCode: "NLG",
    },
    {
      Entity: "NETHERLANDS ANTILLES",
      Currency: "Netherlands Antillean Guilder",
      AlphabeticCode: "ANG",
    },
    {
      Entity: "NICARAGUA",
      Currency: "Cordoba",
      AlphabeticCode: "NIC",
    },
    {
      Entity: "PERU",
      Currency: "Nuevo Sol",
      AlphabeticCode: "PEN",
    },
    {
      Entity: "PERU",
      Currency: "Sol",
      AlphabeticCode: "PEH",
    },
    {
      Entity: "PERU",
      Currency: "Inti",
      AlphabeticCode: "PEI",
    },
    {
      Entity: "PERU",
      Currency: "Sol",
      AlphabeticCode: "PES",
    },
    {
      Entity: "POLAND",
      Currency: "Zloty",
      AlphabeticCode: "PLZ",
    },
    {
      Entity: "PORTUGAL",
      Currency: "Portuguese Escudo",
      AlphabeticCode: "PTE",
    },
    {
      Entity: "RÃ‰UNION",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
    },
    {
      Entity: "ROMANIA",
      Currency: "Leu A/52",
      AlphabeticCode: "ROK",
    },
    {
      Entity: "ROMANIA",
      Currency: "New Romanian Leu",
      AlphabeticCode: "RON",
    },
    {
      Entity: "ROMANIA",
      Currency: "Old Leu",
      AlphabeticCode: "ROL",
    },
    {
      Entity: "RUSSIAN FEDERATION",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUR",
    },
    {
      Entity: "SAINT MARTIN",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
    },
    {
      Entity: "SAINT PIERRE AND MIQUELON",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
    },
    {
      Entity: "SAINT-BARTHÃ‰LEMY",
      Currency: "French Franc",
      AlphabeticCode: "FRF",
    },
    {
      Entity: "SAN MARINO",
      Currency: "Italian Lira",
      AlphabeticCode: "ITL",
    },
    {
      Entity: "SERBIA AND MONTENEGRO",
      Currency: "Serbian Dinar",
      AlphabeticCode: "CSD",
    },
    {
      Entity: "SERBIA AND MONTENEGRO",
      Currency: "Euro",
      AlphabeticCode: "EUR",
    },
    {
      Entity: "SLOVAKIA",
      Currency: "Slovak Koruna",
      AlphabeticCode: "SKK",
    },
    {
      Entity: "SLOVENIA",
      Currency: "Tolar",
      AlphabeticCode: "SIT",
    },
    {
      Entity: "SOUTH AFRICA",
      Currency: "Financial Rand",
      AlphabeticCode: "ZAL",
    },
    {
      Entity: "SOUTH SUDAN",
      Currency: "Sudanese Pound",
      AlphabeticCode: "SDG",
    },
    {
      Entity: "SOUTHERN RHODESIA",
      Currency: "Rhodesian Dollar",
      AlphabeticCode: "RHD",
    },
    {
      Entity: "SPAIN",
      Currency: "Spanish Peseta",
      AlphabeticCode: "ESA",
    },
    {
      Entity: "SPAIN",
      Currency: 'A" Account (convertible Peseta Account)',
      AlphabeticCode: "ESB",
    },
    {
      Entity: "SPAIN",
      Currency: "Spanish Peseta",
      AlphabeticCode: "ESP",
    },
    {
      Entity: "SUDAN",
      Currency: "Sudanese Dinar",
      AlphabeticCode: "SDD",
    },
    {
      Entity: "SUDAN",
      Currency: "Sudanese Pound",
      AlphabeticCode: "SDP",
    },
    {
      Entity: "SURINAME",
      Currency: "Surinam Guilder",
      AlphabeticCode: "SRG",
    },
    {
      Entity: "SWITZERLAND",
      Currency: "WIR Franc (for electronic)",
      AlphabeticCode: "CHC",
    },
    {
      Entity: "TAJIKISTAN",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUR",
    },
    {
      Entity: "TAJIKISTAN",
      Currency: "Tajik Ruble",
      AlphabeticCode: "TJR",
    },
    {
      Entity: "TIMOR-LESTE",
      Currency: "Rupiah",
      AlphabeticCode: "IDR",
    },
    {
      Entity: "TIMOR-LESTE",
      Currency: "Timor Escudo",
      AlphabeticCode: "TPE",
    },
    {
      Entity: "TURKEY",
      Currency: "Old Turkish Lira",
      AlphabeticCode: "TRL",
    },
    {
      Entity: "TURKEY",
      Currency: "New Turkish Lira",
      AlphabeticCode: "TRY",
    },
    {
      Entity: "TURKMENISTAN",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUR",
    },
    {
      Entity: "TURKMENISTAN",
      Currency: "Turkmenistan Manat",
      AlphabeticCode: "TMM",
    },
    {
      Entity: "UGANDA",
      Currency: "Uganda Shilling",
      AlphabeticCode: "UGS",
    },
    {
      Entity: "UGANDA",
      Currency: "Old Shilling",
      AlphabeticCode: "UGW",
    },
    {
      Entity: "UKRAINE",
      Currency: "Karbovanet",
      AlphabeticCode: "UAK",
    },
    {
      Entity: "UNION OF SOVIET SOCIALIST REPUBLICS",
      Currency: "Rouble",
      AlphabeticCode: "SUR",
    },
    {
      Entity: "UNITED STATES",
      Currency: "US Dollar (Same day)",
      AlphabeticCode: "USS",
    },
    {
      Entity: "URUGUAY",
      Currency: "Old Uruguay Peso",
      AlphabeticCode: "UYN",
    },
    {
      Entity: "URUGUAY",
      Currency: "Uruguayan Peso",
      AlphabeticCode: "UYP",
    },
    {
      Entity: "UZBEKISTAN",
      Currency: "Russian Ruble",
      AlphabeticCode: "RUR",
    },
    {
      Entity: "VENEZUELA",
      Currency: "Bolivar",
      AlphabeticCode: "VEB",
    },
    {
      Entity: "VENEZUELA",
      Currency: "Bolivar Fuerte",
      AlphabeticCode: "VEF",
    },
    {
      Entity: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
      Currency: "Bolivar",
      AlphabeticCode: "VEF",
    },
    {
      Entity: "VIETNAM",
      Currency: "Old Dong",
      AlphabeticCode: "VNC",
    },
    {
      Entity: "YEMEN, DEMOCRATIC",
      Currency: "Yemeni Dinar",
      AlphabeticCode: "YDD",
    },
    {
      Entity: "YUGOSLAVIA",
      Currency: "New Yugoslavian Dinar",
      AlphabeticCode: "YUD",
    },
    {
      Entity: "YUGOSLAVIA",
      Currency: "New Dinar",
      AlphabeticCode: "YUM",
    },
    {
      Entity: "YUGOSLAVIA",
      Currency: "Yugoslavian Dinar",
      AlphabeticCode: "YUN",
    },
    {
      Entity: "ZAIRE",
      Currency: "New Zaire",
      AlphabeticCode: "ZRN",
    },
    {
      Entity: "ZAIRE",
      Currency: "Zaire",
      AlphabeticCode: "ZRZ",
    },
    {
      Entity: "ZAMBIA",
      Currency: "Zambian Kwacha",
      AlphabeticCode: "ZMK",
    },
    {
      Entity: "ZIMBABWE",
      Currency: "Rhodesian Dollar",
      AlphabeticCode: "ZWC",
    },
    {
      Entity: "ZIMBABWE",
      Currency: "Zimbabwe Dollar (old)",
      AlphabeticCode: "ZWD",
    },
    {
      Entity: "ZIMBABWE",
      Currency: "Zimbabwe Dollar",
      AlphabeticCode: "ZWD",
    },
    {
      Entity: "ZIMBABWE",
      Currency: "Zimbabwe Dollar (new)",
      AlphabeticCode: "ZWN",
    },
    {
      Entity: "ZIMBABWE",
      Currency: "Zimbabwe Dollar",
      AlphabeticCode: "ZWR",
    },
    {
      Entity: "ZZ01_Gold-Franc",
      Currency: "Gold-Franc",
      AlphabeticCode: "XFO",
    },
    {
      Entity: "ZZ02_RINET Funds Code",
      Currency: "RINET Funds Code",
      AlphabeticCode: "XRE",
    },
    {
      Entity: "ZZ05_UIC-Franc",
      Currency: "UIC-Franc",
      AlphabeticCode: "XFU",
    },
  ],
};
